courses/urls.py
from django.urls import path
from .views import IndexView, CourseListView, ReviewCreateView, mercado_pago_webhook, exam_view, CertificatePDFPrintView, CertificatesListView
from django.views.generic import TemplateView

app_name = 'courses'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('course/<int:pk>/', ReviewCreateView.as_view(), name='course-detail'),
    path('course/my_courses/', CourseListView.as_view(), name='my-courses'),
    path('course/my_certificates/', CertificatesListView.as_view(), name='my-certificates'),
    path('course/mercado_pago_webhook/', mercado_pago_webhook, name='mercado-pago-webhook'),
    path('course/<int:course_id>/exam', exam_view, name='exam'),
    path('course/<int:pk>/pdf/', CertificatePDFPrintView.as_view(), name='certificate-pdf')
]

users/urls.py
from django.urls import path
from .views import profile

app_name = 'users'

urlpatterns = [
    # path("signup/", signup, name="signup"),
    # path("login/", auth_views.LoginView.as_view(template_name = "users/login.html", redirect_authenticated_user = True), name='login'),
    # path("logout/", LogoutUser.as_view(), name='logout'),
    path("profile/", profile, name="profile"),
    # path("activate/<uidb64>/<token>", activate, name='activate')
]

worstatnew/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theme/templates/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<link
			rel="canonical"
			href="https://https://demo.themesberg.com/landwind/"
		/>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
		<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
		<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
		<link rel="manifest" href="{% static 'site.webmanifest' %}">
		<title>{% block title %}{% endblock title %}</title>
		{% tailwind_css %}
		<!-- Meta SEO -->
		<meta name="title" content="Landwind - Tailwind CSS Landing Page" />
		<meta
			name="description"
			content="Impulsando el desarrollo de jóvenes y profesionales en todo el Perú a través de WorStat, la plataforma educativa sobre cursos de software estadísticos y herramientas estadísticas en diferentes áreas de estudio. Nos comprometemos a ofrecer cursos y capacitaciones de software estadístico de la más alta calidad, garantizando un contenido relevante y actualizado."
		/>
		<meta name="robots" content="index, follow" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="language" content="English" />
		<meta name="author" content="Themesberg" />

		<!-- Social media share -->
		<meta property="og:title" content="Landwind - Tailwind CSS Landing Page" />
		<meta property="og:site_name" content="Themesberg" />
		<meta
			property="og:url"
			content="https://https://demo.themesberg.com/landwind/"
		/>
		<meta
			property="og:description"
			content="Impulsando el desarrollo de jóvenes y profesionales en todo el Perú a través de WorStat, la plataforma educativa sobre cursos de software estadísticos y herramientas estadísticas en diferentes áreas de estudio. Nos comprometemos a ofrecer cursos y capacitaciones de software estadístico de la más alta calidad, garantizando un contenido relevante y actualizado."
		/>
		<meta property="og:type" content="" />
		<meta
			property="og:image"
			content="https://themesberg.s3.us-east-2.amazonaws.com/public/github/landwind/og-image.png"
		/>
		<meta name="twitter:card" content="summary" />
		<meta name="twitter:site" content="@themesberg" />
		<meta name="twitter:creator" content="@themesberg" />

		<!-- Favicon -->
		<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
		<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
		<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
		<meta name="msapplication-TileColor" content="#da532c" />
		<meta name="theme-color" content="#ffffff" />
		<script async defer src="https://buttons.github.io/buttons.js"></script>
		<script src="https://kit.fontawesome.com/2c7546181b.js" crossorigin="anonymous"></script>
		<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css" rel="stylesheet" />
	</head>
	<body>
		{% include 'header.html' %}
		{% block content %} {% endblock content %}
		{% include 'footer.html' %}
		{% block script %}
		{% endblock script %}
		<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
	</body>
</html>

theme/templates/footer.html
{% load static %}
<footer class="bg-white ">
    <div class="max-w-screen-xl p-4 py-6 mx-auto lg:py-16 md:p-8 lg:p-10">
        <div class="grid grid-cols-2 gap-8 md:grid-cols-3 lg:grid-cols-5">
            <div>
                <h3 class="mb-6 text-sm font-semibold text-gray-900 uppercase ">Company</h3>
                <ul class="text-gray-500 ">
                    <li class="mb-4">
                        <a href="#" class=" hover:underline">About</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Careers</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Brand Center</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Blog</a>
                    </li>
                </ul>
            </div>
            <div>
                <h3 class="mb-6 text-sm font-semibold text-gray-900 uppercase ">Help center</h3>
                <ul class="text-gray-500 ">
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Discord Server</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Twitter</a>
                    </li>
                    <li class="mb-4">
                     <a href="#" class="hover:underline">Facebook</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Contact Us</a>
                    </li>
                </ul>
            </div>
            <div>
                <h3 class="mb-6 text-sm font-semibold text-gray-900 uppercase ">Legal</h3>
                <ul class="text-gray-500 ">
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Privacy Policy</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Licensing</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Terms</a>
                    </li>
                </ul>
            </div>
            <div>
                <h3 class="mb-6 text-sm font-semibold text-gray-900 uppercase ">Company</h3>
                <ul class="text-gray-500 ">
                    <li class="mb-4">
                        <a href="#" class=" hover:underline">About</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Careers</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Brand Center</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Blog</a>
                    </li>
                </ul>
            </div>
            <div>
                <h3 class="mb-6 text-sm font-semibold text-gray-900 uppercase ">Download</h3>
                <ul class="text-gray-500 ">
                    <li class="mb-4">
                        <a href="#" class="hover:underline">iOS</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Android</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">Windows</a>
                    </li>
                    <li class="mb-4">
                        <a href="#" class="hover:underline">MacOS</a>
                    </li>
                </ul>
            </div>
        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto  lg:my-8">
        <div class="text-center">
            <div class="flex items-center w-24 mx-auto mb-6">
                <a href="" class="flex items-center hover:cursor-default">
                    <img
                        src="{% static 'img/logo.png' %}"
                        class="mr-3"
                        alt="Worstat Logo"
                    />
                </a>
            </div>
            <span class="block text-sm text-center text-gray-500 mb-6">© 2023-2024 Worstat. Todos los derechos reservados.
            </span>
            <ul class="flex justify-center mt-5 space-x-5">
                <li>
                    <a href="https://www.facebook.com/profile.php?id=61556656546256" class="text-gray-500 hover:text-gray-900  ">
                        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" /></svg>
                    </a>
                </li>
                <li>
                    <a href="https://www.instagram.com/wor.stat" class="text-gray-500 hover:text-gray-900  ">
                        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" /></svg>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</footer>

theme/templates/header.html
{% load static %}
<header class="w-full">
    <nav class="bg-white border-gray-200 py-2.5">
        <div
            class="flex flex-wrap items-center justify-between max-w-screen-xl px-4 mx-auto"
        >
            <div class="flex items-center w-24">
                <a href="{% url 'courses:index' %}" class="flex items-center">
                    <img
                        src="{% static 'img/logo.png' %}"
                        class="mr-3"
                        alt="Worstat Logo"
                    />
                </a>
            </div>
            <div class="flex items-center lg:order-2">
                {% if user.is_authenticated %}
                <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse w-24 justify-end">
                    <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 " id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
                      <span class="sr-only">Open user menu</span>
                      <img class="w-8 h-8 rounded-full" src="{% if user.picture %}{{ user.picture.url }}{% else %}{% static 'img/default_profile.jpg' %}{% endif %}" alt="user photo">
                    </button>
                    <!-- Dropdown menu -->
                    <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow  " id="user-dropdown">
                      <div class="px-4 py-3">
                        <span class="block text-sm text-gray-900 ">{{ user.full_name }}</span>
                        <span class="block text-sm  text-gray-500 truncate ">{{ user }}</span>
                      </div>
                      <ul class="py-2" aria-labelledby="user-menu-button">
                        <li>
                          <a href="{% url 'users:profile' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Perfil</a>
                        </li>
                        <li>
                          <a href="{% url 'courses:my-courses' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Mis Cursos</a>
                        </li>
                        <li>
                          <a href="{% url 'courses:my-certificates' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Mis Certificados</a>
                        </li>
                        {% if user.is_superuser or user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Administracion</a>
                        </li>
                        {% endif %}
                        <li>
                          <a href="{% url 'account_change_password' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100   ">Cambiar contraseña</a>
                        </li>
                        <li>
                          <a href="{% url 'account_logout' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100   ">Cerrar sesión</a>
                        </li>
                      </ul>
                    </div>
                    <button
                    data-collapse-toggle="mobile-menu-2"
                    type="button"
                    class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    aria-controls="mobile-menu-2"
                    aria-expanded="false"
                >
                    <span class="sr-only">Open main menu</span>
                    <svg
                        class="w-6 h-6"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                            clip-rule="evenodd"
                        ></path>
                    </svg>
                    <svg
                        class="hidden w-6 h-6"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"
                        ></path>
                    </svg>
                </button>
                </div>
                {% else %}
                <a
                    href="{% url 'account_login' %}"
                    class="text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 sm:mr-2 lg:mr-4 focus:outline-none"
                    >Iniciar Sesión</a
                >
                <a
                    href="{% url 'account_signup' %}"
                    class="text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 sm:mr-2 lg:mr-0 focus:outline-none"
                    >Registrarse</a
                >
                <button
                    data-collapse-toggle="mobile-menu-2"
                    type="button"
                    class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    aria-controls="mobile-menu-2"
                    aria-expanded="false"
                >
                    <span class="sr-only">Open main menu</span>
                    <svg
                        class="w-6 h-6"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                            clip-rule="evenodd"
                        ></path>
                    </svg>
                    <svg
                        class="hidden w-6 h-6"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"
                        ></path>
                    </svg>
                </button>
                {% endif %}
            </div>
            <div
                class="items-center justify-between hidden w-full lg:flex lg:w-auto lg:order-1"
                id="mobile-menu-2"
            >
                <ul
                    class="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0"
                >
                    <li>
                        <a
                            href="{% url 'courses:index' %}"
                            class="block py-2 pl-3 pr-4 text-white bg-purple-700 rounded lg:bg-transparent lg:text-purple-700 lg:p-0"
                            aria-current="page"
                            >Home</a
                        >
                    </li>
                    <li>
                        <a
                            href="{% url 'courses:index' %}#cursos"
                            class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-purple-700 lg:p-0"
                            >Cursos</a
                        >
                    </li>
                    <li>
                        <a
                            href="{% url 'courses:index' %}#contact"
                            class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-purple-700 lg:p-0"
                            >Contacto</a
                        >
                    </li>
                    <li>
                        <a
                            href="{% url 'courses:index' %}#about"
                            class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-purple-700 lg:p-0"
                            >Nosotros</a
                        >
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <hr>
</header>