courses/urls.py
from django.urls import path
from .views import IndexView, CourseListView, ReviewCreateView, mercado_pago_webhook, exam_view, CertificatePDFPrintView, CertificatesListView
from django.views.generic import TemplateView

app_name = 'courses'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('course/<int:pk>/', ReviewCreateView.as_view(), name='course-detail'),
    path('course/my_courses/', CourseListView.as_view(), name='my-courses'),
    path('course/my_certificates/', CertificatesListView.as_view(), name='my-certificates'),
    path('course/mercado_pago_webhook/', mercado_pago_webhook, name='mercado-pago-webhook'),
    path('course/<int:course_id>/exam', exam_view, name='exam'),
    path('course/<int:pk>/pdf/', CertificatePDFPrintView.as_view(), name='certificate-pdf')
]

users/urls.py
from django.urls import path
from .views import profile

app_name = 'users'

urlpatterns = [
    # path("signup/", signup, name="signup"),
    # path("login/", auth_views.LoginView.as_view(template_name = "users/login.html", redirect_authenticated_user = True), name='login'),
    # path("logout/", LogoutUser.as_view(), name='logout'),
    path("profile/", profile, name="profile"),
    # path("activate/<uidb64>/<token>", activate, name='activate')
]

worstatnew/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import timedelta
import cv2
import datetime

# Create your models here.

class Course(models.Model):

    class Level(models.TextChoices):
        BEGINNER = "BG", "Principiante"
        INTERMEDIATE = "IN", "Intermedio"
        ADVANCED = "AD", "Avanzado"

    title = models.CharField("Titulo", max_length=255)
    description = models.CharField("Descripcion", max_length=255)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, verbose_name="users", through='Enrollment')
    price = models.DecimalField("Precio", max_digits=5, decimal_places=2, validators=[MinValueValidator(0)])
    level = models.CharField("Nivel", choices=Level.choices, max_length=2)
    published_date = models.DateField('Fecha de publicacion', default=timezone.now)
    picture = models.ImageField(verbose_name="Imagen", max_length=500, upload_to='users', null=True)
    preference = models.JSONField(default=dict, editable=False)

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"

    def __str__(self) -> str:
        return f'{self.title}'

    def get_duration(self):
        sections = Section.objects.filter(course=self)
        total_duration = sum(section.get_duration() for section in sections)
        return total_duration

    def get_duration_display(self):
        seconds = self.get_duration()
        seconds_timedelta = timedelta(seconds=seconds)
        hours, remainder = divmod(seconds_timedelta.seconds, 3600)
        minutes, _ = divmod(remainder, 60)
        formatted_duration = f"{hours:02} h {minutes:02} m"
        return formatted_duration

    def get_num_episodes(self):
        # Retorna el número de episodios relacionados con este curso
        return sum(section.episode_set.count() for section in self.section_set.all())

class Question(models.Model):
    course = models.ForeignKey(Course, verbose_name='Curso', on_delete=models.CASCADE)
    question = models.CharField("Pregunta", max_length=1000)

    class Meta:
        verbose_name = "Pregunta"
        verbose_name_plural = "Preguntas"

    def __str__(self) -> str:
        return f'{self.course}: {self.question}'

class Answer(models.Model):
    question = models.ForeignKey(Question, verbose_name="Pregunta", on_delete=models.CASCADE)
    answer = models.CharField("Respuesta", max_length=1000, blank=False)
    is_correct = models.BooleanField("Correcto", default=False)

    class Meta:
        verbose_name = "Respuesta"
        verbose_name_plural = "Respuestas"

    def __str__(self) -> str:
        return f'{self.question}: {self.answer}'

class Enrollment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Usuario", on_delete=models.CASCADE)
    course = models.ForeignKey(Course, verbose_name='Curso', on_delete=models.CASCADE)
    enrollment_date = models.DateField('Fecha de inscripcion', default=timezone.now)
    is_completed = models.BooleanField('Completado', default=False)
    
    class Meta:
        verbose_name = "Matricula"
        verbose_name_plural = "Matriculas"
        unique_together = ["user", "course"]

    def __str__(self) -> str:
        return f'{self.user} enrolled in {self.course}'

class Section(models.Model):
    title = models.CharField(verbose_name="titulo", max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="curso")
    order = models.PositiveSmallIntegerField("orden")

    def __str__(self) -> str:
        return f'{self.course}: {self.title}'

    def get_duration(self):
        # get the duration of all the episodes in this section
        episodes = Episode.objects.filter(section=self)
        total_duration = sum(episode.duration for episode in episodes)
        return total_duration

    def get_duration_display(self):
        seconds = self.get_duration()
        seconds_timedelta = timedelta(seconds=seconds)
        hours, remainder = divmod(seconds_timedelta.seconds, 3600)
        minutes, _ = divmod(remainder, 60)
        formatted_duration = f"{hours:02} h {minutes:02} m"
        return formatted_duration

    class Meta:
        ordering = ['order']
        verbose_name = "Seccion"
        verbose_name_plural = "Secciones"

def get_upload_to(instance, filename):
    return f'{instance.section.course.title}/{instance.section.title}/{instance.order}-{filename}'

def get_upload_file_to(instance, filename):
    return f'{instance.section.course.title}/{instance.section.title}/{instance.order}-{filename}-file'

class Episode(models.Model):

    title = models.CharField(max_length=255)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    order = models.PositiveSmallIntegerField("Orden")
    video = models.FileField('Video', upload_to=get_upload_to, max_length=500)
    duration = models.PositiveIntegerField("Duracion", default=0)
    free = models.BooleanField("Gratis", default=False)
    file = models.FileField("Archivo", upload_to=get_upload_file_to, max_length=500, null=True, blank=True)

    def __str__(self) -> str:
        return f'{self.section}:{self.order}-{self.title}'

    def get_duration(self):
        try:
            data = cv2.VideoCapture(self.video.url)
            frames = data.get(cv2.CAP_PROP_FRAME_COUNT) 
            fps = data.get(cv2.CAP_PROP_FPS)
            seconds = round(frames / fps) 
            return seconds
        except Exception as e:
            print(f"Error calculating duration for {self.title}: {e}")
    
    class Meta:
        ordering = ['order']
        verbose_name = "Clase"
        verbose_name_plural = "Clases"

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Usuario", on_delete=models.CASCADE)
    course = models.ForeignKey(Course, verbose_name='Curso', on_delete=models.CASCADE)
    comment = models.TextField("Comentario")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    # rating = models.PositiveSmallIntegerField("Calificacion", validators=[MaxValueValidator(5)], default=1)

    class Meta:
        verbose_name = 'Reseña'
        verbose_name_plural = 'Reseñas'

    def __str__(self) -> str:
        return f'{self.comment}'

class Transaction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="user", on_delete=models.CASCADE)
    course = models.ForeignKey(Course, verbose_name='course', on_delete=models.CASCADE)
    transaction_date = models.DateTimeField("transaction date", auto_now=True)
    amount = models.DecimalField("amount", max_digits=5, decimal_places=2)

    def __str__(self) -> str:
        return f'Transaction on {self.course} by {self.user}: S/{self.amount}'

courses/forms.py
from django import forms
from .models import Review
from users.models import Contact

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment']

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

courses/templates/courses/certificate_pdf.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Certificado de Completación</title>
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
			crossorigin="anonymous"
		/>
		<style>
			@page {
				size: landscape;
			}

			@import url("https://fonts.googleapis.com/css?family=Open+Sans|Pinyon+Script|Rochester");

			.cursive {
				font-family: "Pinyon Script", cursive;
			}

			.sans {
				font-family: "Open Sans", sans-serif;
			}

			.bold {
				font-weight: bold;
			}

			.block {
				display: block;
			}

			.underline {
				border-bottom: 1px solid #777;
				padding: 5px;
				margin-bottom: 15px;
			}

			.margin-0 {
				margin: 0;
			}

			.padding-0 {
				padding: 0;
			}

			.pm-empty-space {
				height: 40px;
				width: 100%;
			}

			body {
				padding: 20px 0;
				background: #ccc;
			}

			.pm-certificate-container {
				position: relative;
				width: 800px;
				height: 600px;
				background-color: #618597;
				padding: 30px;
				color: #333;
				font-family: "Open Sans", sans-serif;
				box-shadow: 0 0 5px rgba(0, 0, 0, 0.5);
			}

			.pm-certificate-container .outer-border {
				width: 794px;
				height: 594px;
				position: absolute;
				left: 50%;
				margin-left: -397px;
				top: 50%;
				margin-top: -297px;
				border: 2px solid #fff;
			}

			.pm-certificate-container .inner-border {
				width: 730px;
				height: 530px;
				position: absolute;
				left: 50%;
				margin-left: -365px;
				top: 50%;
				margin-top: -265px;
				border: 2px solid #fff;
			}

			.pm-certificate-container .pm-certificate-border {
				position: relative;
				width: 720px;
				height: 520px;
				padding: 0;
				border: 1px solid #e1e5f0;
				background-color: rgba(255, 255, 255, 1);
				background-image: none;
				left: 50%;
				margin-left: -360px;
				top: 50%;
				margin-top: -260px;
			}

			.pm-certificate-container .pm-certificate-border .pm-certificate-block {
			}

			.pm-certificate-container .pm-certificate-border .pm-certificate-header {
				margin-bottom: 10px;
			}

			.pm-certificate-container .pm-certificate-border .pm-certificate-title {
				position: relative;
				top: 40px;
			}

			.pm-certificate-container
				.pm-certificate-border
				.pm-certificate-title
				h2 {
				font-size: 34px !important;
			}

			.pm-certificate-container .pm-certificate-border .pm-certificate-body {
				padding: 20px;
			}

			.pm-certificate-container
				.pm-certificate-border
				.pm-certificate-body
				.pm-name-text {
				font-size: 20px;
			}

			.pm-certificate-container .pm-certificate-border .pm-earned {
				margin: 15px 0 20px;
			}

			.pm-certificate-container
				.pm-certificate-border
				.pm-earned
				.pm-earned-text {
				font-size: 20px;
			}

			.pm-certificate-container
				.pm-certificate-border
				.pm-earned
				.pm-credits-text {
				font-size: 15px;
			}

			.pm-certificate-container
				.pm-certificate-border
				.pm-course-title
				.pm-earned-text {
				font-size: 20px;
			}

			.pm-certificate-container
				.pm-certificate-border
				.pm-course-title
				.pm-credits-text {
				font-size: 15px;
			}

			.pm-certificate-container .pm-certificate-border .pm-certified {
				font-size: 12px;
			}

			.pm-certificate-container
				.pm-certificate-border
				.pm-certified
				.underline {
				margin-bottom: 5px;
			}

			.pm-certificate-container .pm-certificate-border .pm-certificate-footer {
				
			}

			/* Continue similarly for the rest of the nested styles */
		</style>
	</head>
	<body class="bg-slate-950">
		<div class="container pm-certificate-container">
			<div class="outer-border"></div>
			<div class="inner-border"></div>

			<div class="pm-certificate-border col-xs-12">
				<div class="row pm-certificate-header">
					<div class="pm-certificate-title cursive col-xs-12 text-center">
						<h2>Worstat Certificado</h2>
					</div>
				</div>

				<div class="row pm-certificate-body">
                    
					<div class="pm-certificate-block">
                        
						<div class="col-xs-12">
							<div class="row">
								<div class="col-xs-2"><!-- LEAVE EMPTY --></div>
								<div
									class="pm-certificate-name underline margin-0 col-xs-8 text-center"
								>
									<span class="pm-name-text bold">{% if enrollment.user.full_name %}{{enrollment.user.full_name}}{% else %}{{enrollment.user}}{% endif %}</span>
								</div>
								<div class="col-xs-2"><!-- LEAVE EMPTY --></div>
							</div>
						</div>

						<div class="col-xs-12">
							<div class="row">
								<div class="col-xs-2"><!-- LEAVE EMPTY --></div>
								<div class="pm-earned col-xs-8 text-center">
									<span class="pm-earned-text padding-0 block cursive"
										>ha completado exitosamente</span
									>
								</div>
								<div class="col-xs-2"><!-- LEAVE EMPTY --></div>
								<div class="col-xs-12"></div>
							</div>
						</div>

						<div class="col-xs-12">
							<div class="row">
								<div class="col-xs-2"><!-- LEAVE EMPTY --></div>
								<div class="pm-course-title col-xs-8 text-center">
									<span class="pm-earned-text block cursive"
										>el curso titulado</span
									>
								</div>
								<div class="col-xs-2"><!-- LEAVE EMPTY --></div>
							</div>
						</div>

						<div class="col-xs-12">
							<div class="row">
								<div class="col-xs-2"><!-- LEAVE EMPTY --></div>
								<div class="pm-course-title underline col-xs-8 text-center">
									<span class="pm-credits-text block bold sans"
										>{{ enrollment.course.title }}</span
									>
								</div>
								<div class="col-xs-2"><!-- LEAVE EMPTY --></div>
							</div>
						</div>
					</div>

					<div class="col-xs-12">
						<div class="row">
							<div class="pm-certificate-footer">
								<div class="col-xs-4 pm-certified col-xs-4 text-center">
									<span class="pm-credits-text block sans"
										>Buffalo City School District</span
									>
									<span class="pm-empty-space block underline"></span>
									<span class="bold block"
										>Crystal Benton Instructional Specialist II, Staff
										Development</span
									>
								</div>
								<div class="col-xs-4">
									<!-- LEAVE EMPTY -->
								</div>
								<div class="col-xs-4 pm-certified col-xs-4 text-center">
									<span class="pm-credits-text block sans">Date Completed</span>
									<span class="pm-empty-space block underline"></span>
									<span class="bold block">DOB: </span>
									<span class="bold block"
										>Social Security # (last 4 digits)</span
									>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
			crossorigin="anonymous"
		></script>
	</body>
</html>

courses/templates/courses/exam.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="">
    <div class="bg-gray-900 p-16">
        <h2 class="max-w-screen-xl mx-auto text-white font-bold text-5xl">{{ course.title }} - Examen de certificacion </h2>
    </div>
    <div class="mt-16 max-w-screen-xl mx-auto">
        <form method="post" action="{% url 'courses:exam' course.id %}">
            {% csrf_token %}
            {% for question in questions %}
              <div class="mb-16">
                <h3 class="mb-4 font-semibold text-gray-900 text-2xl">{{ question.question }}</h3>
                <ul class="w-full text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg">
                  {% for answer in question.answer_set.all %}
                    <li class="w-full border-b border-gray-200 rounded-t-lg hover:bg-slate-100">
                      <div class="flex items-center ps-3">
                        <input type="radio" id="answer{{ answer.id }}" name="question{{ question.id }}" value="{{ answer.id }}" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500">
                        <label for="answer{{ answer.id }}" class="w-full py-3 ms-2 text-lg text-gray-900">{{ answer.answer }}</label>
                      </div>
                    </li>
                  {% endfor %}
                </ul>
              </div>
            {% endfor %}
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Enviar Respuestas</button>
        </form>
</section>
{% endblock %}

courses/templates/courses/my_certificates.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="min-h-screen">
    <div class="bg-gray-900 p-16">
        <h2 class="max-w-screen-xl mx-auto text-white font-bold text-5xl">Mis certificados</h2>
    </div>
    <div class="w-full p-8">
        <ul class="list-disc pl-5">
            {% for message in messages %}
            <li class="{{ message.tags }} text-gray-700">{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    <div class="mt-16">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mx-auto max-w-screen-xl">
            {% for enrollment in enrollments %}
            <div class="rounded-3xl overflow-hidden shadow-2xl p-5 flex flex-col">
                <img class="w-full rounded-3xl block" src="{{ enrollment.course.picture.url }}" alt="{{ enrollment.course.title }}">
                <div class="flex justify-between flex-col mt-0 h-full">
                    <div class="font-bold text-xl mb-2">{{ enrollment.course.title }}</div>
                    <div>
                        <hr>
                        <div class="flex justify-between mt-4 items-center text-gray-500">
                            <a href="{% url 'courses:certificate-pdf' pk=enrollment.pk %}" class="text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 sm:mr-2 lg:mr-4 focus:outline-none">
                                Ver certificado
                            </a>
                            <div class="">
                                {{ enrollment.course.get_level_display }}
                            </div>
                        </div>
                    </div>
                </div>            
            </div>
            {% endfor %}
        </div>
        {% if enrollments %}
        {% else %}
        <h1 class="text-4xl mx-auto max-w-screen-xl">Usted aun no ha finalizado algun curso</h1>
        {% endif %}
    </div>
</section>
{% endblock content %}

courses/templates/courses/my_courses.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="min-h-screen">
    <div class="bg-gray-900 p-16">
        <h2 class="max-w-screen-xl mx-auto text-white font-bold text-5xl">Mis cursos</h2>
    </div>
    <div class="mt-16">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mx-auto max-w-screen-xl">
            {% for course in courses %}
            <a href="{% url 'courses:course-detail' pk=course.pk %}" class="rounded-3xl overflow-hidden shadow-2xl p-5 flex flex-col">
                <div>
                    <img class="rounded-3xl w-full h-48" src="{{ course.picture.url }}" alt="{{ course.title }}">
                </div>
                <div class="flex justify-between flex-col mt-0 h-full">
                    <div class="font-bold text-xl mb-2">{{ course.title }}</div>
                    <div>
                        <hr>
                        <div class="flex justify-between mt-4 items-center text-gray-500">
                            <div>
                                S/{{ course.price }}
                            </div>
                            <div class="">
                                {{ course.get_level_display }}
                            </div>
                        </div>
                    </div>
                </div>            
            </a>
            {% endfor %}
        </div>
        {% if courses %}
        {% else %}
        <h1 class="text-4xl mx-auto max-w-screen-xl">Usted aun no ha comprado algun curso</h1>
        {% endif %}
    </div>
</section>
{% endblock content %}